Controllers/ImageController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Threading.Tasks;


namespace ImageMongoDb.Controllers
{
    public class ImageController : Controller
    {

        private readonly ImageService _imageService;

        public ImageController(ImageService imageService)

        {
            _imageService = imageService;
        }

        public ActionResult Index()
        {
            var baseUrl = string.Format("{0}://{1}", HttpContext.Request.Scheme, HttpContext.Request.Host);
            ViewBag.baseUrl = baseUrl;
            return View();
        }

        public ActionResult GetImageList()
        {
            //var url = string.Format("{0}://{1}{2}{3}", HttpContext.Request.Scheme, HttpContext.Request.Host, HttpContext.Request.Path, HttpContext.Request.QueryString);
            var baseUrl = string.Format("{0}://{1}", HttpContext.Request.Scheme, HttpContext.Request.Host);
            ViewBag.baseUrl = baseUrl;
            return View();
        }
        public ActionResult GetImages()
        {
            return View();
        }

       
        [HttpGet]
        public async Task<JsonResult> GetData()
        {

            //var res = from mod in _genericRepository.GetAll()
            //          select mod;
            //res.AsEnumerable<ImageToDBW>()
            //  return Json(_genericRepository.GetAll(), JsonRequestBehavior.AllowGet);

           // var collection = GetCollection();
           // var imgdoc = collection.Find(new BsonDocument()).ToList();
            //List<Image> imageList = new List<Image>();
            //foreach (var img in imagelist)
            //{
            //    imageList.Add(new Image
            //    {
            //        id = img.id,
            //        ImageName = img.ImageName,
            //        show = img.show

            //    });
            //}
            var imgdoc = await _imageService.GetAsync();

            return Json(imgdoc);
           
        }

        [HttpGet]
        public ActionResult GetImage()
        {
            return View();
        }

            public async Task<ActionResult> RetrieveImageFile(string id)
         {


            // var filter = Builders<ImageDocument>.Filter.Eq("_id", id);
            //  var collection = GetCollection();




            //  var imageDoc = await collection.FindAsync<ImageDocument>(filter).ConfigureAwait(false);
            //var imageDoc = collection.Find(
            //       q => q.Id == id).FirstOrDefault();
            var imageDoc = await _imageService.GetAsync(id);
            byte[] cover = imageDoc.ContentImage;
            if (cover != null)
            {
                return File(cover, "image/jpg");
            }
            else
            {
                return null;
            }
        }

        [DataContract]
        public class ChunkMetaData
        {
            [DataMember(Name = "uploadUid")]
            public string UploadUid { get; set; }
            [DataMember(Name = "fileName")]
            public string FileName { get; set; }
            [DataMember(Name = "contentType")]
            public string ContentType { get; set; }
            [DataMember(Name = "chunkIndex")]
            public long ChunkIndex { get; set; }
            [DataMember(Name = "totalChunks")]
            public long TotalChunks { get; set; }
            [DataMember(Name = "totalFileSize")]
            public long TotalFileSize { get; set; }
        }

        public class FileResult
        {
            public bool uploaded { get; set; }
            public string fileUid { get; set; }
        }

        [HttpPost]
        public ActionResult Submit(List<IFormFile>  files)
        {
            if (files != null)
            {
                TempData["UploadedFiles"] = GetFileInfo(files);
            }

            return RedirectToRoute("Demo", new { section = "upload", example = "result" });
        }

        public async Task<ActionResult> Save(List<IFormFile>  files)
        {
            // The Name of the Upload component is "files"
               if (files != null)
            {
                foreach (var file in files)
                {
                    string theFileName = Path.GetFileName(file.FileName);

                    //get the bytes from the content stream of the file
                    byte[] thePictureAsBytes = new byte[file.Length];
                   ImageDocument imagedocument = new ImageDocument();
                    using (var ms = new MemoryStream())
                    {
                        file.CopyTo(ms);
                        var fileBytes = ms.ToArray();
                        string s = Convert.ToBase64String(fileBytes);
                        imagedocument.ContentImage = fileBytes;
                    }
                    //   imagedocument.ContentImage = thePictureAsBytes;
                    // Some browsers send file names with full path. This needs to be stripped.
                    //var fileName = Path.GetFileName(file.FileName);
                    //var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileName);

                    //   _imageRepository.Add(imagedocument);

                    //// it will be null
                    //var testProduct = await _imageRepository.GetById(imagedocument.Id);

                    // If everything is ok then:
                    //      await _uow.Commit();

                    // The product will be added only after commit
                    //   testProduct = await _productRepository.GetById(product.Id);

                    //  return Ok(testProduct);
                    // The files are not actually saved in this demo
                    // file.SaveAs(physicalPath);

                    //var id = new ObjectId();
                    //imagedocument.Id = Convert.ToString(id);
                    //    var collection = GetCollection();
                    //collection.InsertOne(imagedocument);
                    await _imageService.CreateAsync(imagedocument);
                }
            }

            // Return an empty string to signify success
            return Content("");
        }

        public ActionResult Remove(string[] fileNames)
        {
            // The parameter of the Remove action must be called "fileNames"

            if (fileNames != null)
            {
                foreach (var fullName in fileNames)
                {
                    var fileName = Path.GetFileName(fullName);
                    //  var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                    var physicalPath = Path.Combine("", fileName);
                    // TODO: Verify user permissions

                    if (System.IO.File.Exists(physicalPath))
                    {
                        // The files are not actually removed in this demo
                        // System.IO.File.Delete(physicalPath);
                    }
                }
            }

            // Return an empty string to signify success
            return Content("");
        }

        public void AppendToFile(string fullPath, Stream content)
        {
            try
            {
                using (FileStream stream = new FileStream(fullPath, FileMode.Append, FileAccess.Write, FileShare.ReadWrite))
                {
                    using (content)
                    {
                        content.CopyTo(stream);
                    }
                }
            }
            catch (IOException ex)
            {
                throw ex;
            }
        }

        public async Task<ActionResult> ChunkSave(List<IFormFile>  files, string metaData)
        {
            if (metaData == null)
            {
                return await Save(files);
            }

            MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(metaData));
            var serializer = new DataContractJsonSerializer(typeof(ChunkMetaData));
            ChunkMetaData somemetaData = serializer.ReadObject(ms) as ChunkMetaData;
            string path = String.Empty;
            // The Name of the Upload component is "files"
            if (files != null)
            {
                foreach (var file in files)
                {
                    //get the bytes from the content stream of the file
                    byte[] thePictureAsBytes = new byte[file.Length];
                    ImageDocument imagedocument = new ImageDocument();
                    imagedocument.ContentImage = thePictureAsBytes;

                    // Some browsers send file names with full path. This needs to be stripped.
                    //var fileName = Path.GetFileName(file.FileName);
                    //var physicalPath = Path.Combine(Server.MapPath("~/App_Data"), fileName);

                    //     _imageRepository.Add(imagedocument);

                    //// it will be null
                    //var testProduct = await _imageRepository.GetById(imagedocument.Id);

                    // If everything is ok then:
                    ///  await _uow.Commit();
                    ///  
                    var id = new ObjectId();
                    imagedocument.Id = Convert.ToString(id);
                    var collection = GetCollection();
                    collection.InsertOne(imagedocument);
                }
            }

            FileResult fileBlob = new FileResult();
            fileBlob.uploaded = somemetaData.TotalChunks - 1 <= somemetaData.ChunkIndex;
            fileBlob.fileUid = somemetaData.UploadUid;

            return Json(fileBlob);
        }

        private IEnumerable<string> GetFileInfo(List<IFormFile>  files)
        {
            return
                from a in files

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ImageMongoDb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.common.min.css" />
    <link rel="stylesheet" href="https://kendo.cdn.telerik.com/2022.1.119/styles/kendo.blueopal.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>




</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ImageMongoDb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="Index">Save</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Image" asp-action="GetImageList">Show</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ImageMongoDb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
 
    <script src="https://kendo.cdn.telerik.com/2022.1.119/js/kendo.all.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>